#### application.yml
server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t7g6NwNWnWX2waLvP2h
      keysecret: JVAHKA1BwHcQsIU8O4fIJRRBEaYbHy
      bucketname: onlieedeu
