#### application.yml
server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: chai960619
  hikari:
    connection-test-query: SELECT 1
    connection-timeout: 60000
    idle-timeout: 500000
    max-lifetime: 540000
    maximum-pool-size: 12
    minimum-idle: 10
    pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  type-aliases-package: com.chai.eduservice.entity.po  # 实体类所在包
  mapper-locations: classpath:/com/chai/eduservice/mapper/auto/*.xml
logging:
  config: classpath:logback-spring.xml
  level:
    com.chai.*: debug
