spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: chai960619
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl