server:
  port: 8081
spring:
  redis:
    host: 192.168.2.132
    password: lu520
    port: 6379
    lettuce:
      pool:
        max-active: 6
        max-idle: 10
        min-idle: 2
    timeout: 2000
